POST http://localhost:8081/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDQ5MDExNjl9.w16pt0iksd2KQco2J2fKwhHEMXt2PrQh4rJIMwer72g

{
    "text": "Test Todo"
}