version: '3.8'
services:
  todo-db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=P!ssw0rd
      - MARIADB_DATABASE=todos

  todo-api:
    image: suptarr/todo-api:1.0
    build: 
      dockerfile: Dockerfile
      context: .
    depends_on:
      - todo-db
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      - SIGN=VnP1vUHdpqtzXJLafBMzGg
      - DB_CONN=root:P!ssw0rd@tcp(todo-db:3306)/todos?charset=utf8mb4&parseTime=True&loc=Local
    restart: always