version: '3.8'
services:
  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=P!ssw0rd
      - MARIADB_DATABASE=todos

  api:
    image: suptarr/todo-api:1.0
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=8081
      - SIGN=VnP1vUHdpqtzXJLafBMzGg
      - DB_CONN=root:P!ssw0rd@tcp(db:3306)/todos?charset=utf8mb4&parseTime=True&loc=Local
    restart: always